import express from 'express';
import ejs from 'ejs';
import bodyParser from 'body-parser';
import methodOverride from 'method-override';
import morgan from 'morgan';
import compression from 'compression';
import helmet from 'helmet';
import cors from 'cors';
import path from 'path';
import LoggerStream from './logger-stream';
import { logs } from './vars';
import { routes, userRouter } from '../routes';
import notFoundException from '../middlewares/exception/not-found-exception';
import errorHandler from '../middlewares/exception/error-handler';

const app = express();
app.use(morgan(logs, { stream: new LoggerStream() }));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));
app.use(methodOverride());
app.use(cors());
app.use(helmet());
app.use(compression());
app.use(express.static(path.join(__dirname, '../public')));
app.set('views', path.join(__dirname, '../views'));
app.engine('html', require('ejs').renderFile);
app.set('view engine', 'html');
app.use('/', routes);
app.use('/api/users', userRouter);
app.use(notFoundException);
app.use(errorHandler);

export default app;
